services:
  bot:
    build: .
    container_name: rodnulya-bot
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    ports:
      - "8080:8080"       # Expose webhook port
    volumes:
      - ./logs:/app/logs  # Persistent storage for logs
      - ./data:/app/data  # Persistent storage for resources
    networks:
      - rodnulya_network

  postgres:
    image: postgres:16-alpine
    container_name: rodnulya-postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rodnulya"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rodnulya_network

networks:
  rodnulya_network:
    external: false
